#!/bin/bash

function github() # $name $addr
{
  [ ! -d "$1"  ] && git clone "https://github.com/$2" "$1"
  cd "$1"; git pull ; cd ..
}

wget -r -l 1 -nd -nc -e robots=off -A '*.pdf,*.tar.gz' https://password-hashing.net/candidates.html

github Argon khovratovich/Argon.git
github Argon2 khovratovich/Argon2.git
github Lyra  leocalm/Lyra.git
github Catena cforler/catena.git
github Pufferfish epixoip/pufferfish.git
