#!/bin/bash

function run() # $1 name $2 log $3 from $4 to
{
	echo "[$(date --rfc-3339=seconds)] -- $2 / $1 --"

	[ ! -d $2 ] && mkdir $2
	OUT=$2/$1.dat
	for i in $(seq $3 $4 $5); do
		../tst-$1 -f $OUT -w -r 3 $6 $i
		echo -n "[$i]"
	done
	echo
	echo "[$(date --rfc-3339=seconds)] --"
}

# G1 tcost MIN, mcost variable
PAR="-s 16 -i 32 -o 32 "
run argon            m_cost 0    100     8000 "$PAR -t 0 -m "
run argon-aesni      m_cost 0    100     8000 "$PAR -t 0 -m "
run argon2d          m_cost 0    100     8000 "$PAR -t 0 -m "
run argon2i          m_cost 0    100     8000 "$PAR -t 0 -m "
run battcrypt        m_cost 0      1       16 "$PAR -t 0 -m "
run catena-butterfly m_cost 0      1       24 "$PAR -t 1 -m "
run catena-dragonfly m_cost 0      1       24 "$PAR -t 1 -m "
run lyra2            m_cost 0    200     9000 "$PAR -t 1 -m "
run lyra2-sse        m_cost 0    200     9000 "$PAR -t 1 -m "
#run makwa           m_cost 0      1       20 "$PAR -t 0 -m " # no mcost
#run parallel        m_cost 0      1     2000 "$PAR -t 0 -m " # no mcost
run pomelo           m_cost 0      1       17 "$PAR -t 0 -m "
run pomelo-sse       m_cost 0      1       17 "$PAR -t 0 -m "
run pufferfish       m_cost 0      1       15 "$PAR -t 0 -m "
run yescrypt         m_cost 0      1       20 "$PAR -t 0 -m "
run yescrypt-sse     m_cost 0      1       20 "$PAR -t 0 -m "

# G2 mcost min, tcost variable
PAR="-s 16 -i 32 -o 32 "
run argon            t_cost 0     10      260 "$PAR -m    500 -t "
run argon-aesni      t_cost 0     10      260 "$PAR -m    500 -t "
run argon2d          t_cost 0     10      250 "$PAR -m    500 -t "
run argon2i          t_cost 0     10      260 "$PAR -m    500 -t "
run battcrypt        t_cost 0      1       20 "$PAR -m      5 -t "
run catena-butterfly t_cost 0      5      100 "$PAR -m     14 -t "
run catena-dragonfly t_cost 0      5      100 "$PAR -m     14 -t "
run lyra2            t_cost 0   1000    20000 "$PAR -m    100 -t "
run lyra2-sse        t_cost 0   1000    20000 "$PAR -m    100 -t "
run makwa            t_cost 0  10000   300000 "$PAR -m      0 -t "
run parallel         t_cost 0      1       26 "$PAR -m      0 -t "
run pomelo           t_cost 0      1       15 "$PAR -m      5 -t "
run pomelo-sse       t_cost 0      1       15 "$PAR -m      5 -t "
run pufferfish       t_cost 0      1        9 "$PAR -m     10 -t "
run yescrypt         t_cost 0     10      300 "$PAR -m     10 -t "
run yescrypt-sse     t_cost 0     10      300 "$PAR -m     10 -t "

# G3 input len 1-MAX, mcost, tcost, output fixed
PAR="-h -s 16 -o 32 "
MAX=300
STEP=1
run argon            i_len 1 $STEP $MAX "$PAR -m     0 -t  2000 -i "
run argon-aesni      i_len 1 $STEP $MAX "$PAR -m     0 -t  1500 -i "
run argon2d          i_len 1 $STEP $MAX "$PAR -m   100 -t   255 -i "
run argon2i          i_len 1 $STEP $MAX "$PAR -m   100 -t  2000 -i "
run battcrypt        i_len 1 $STEP $MAX "$PAR -m     0 -t    17 -i "
run catena-dragonfly i_len 1 $STEP $MAX "$PAR -m    14 -t   100 -i "
run catena-butterfly i_len 1 $STEP $MAX "$PAR -m    10 -t    60 -i "
run lyra2            i_len 1 $STEP $MAX "$PAR -m     6 -t  2000 -i "
run lyra2-sse        i_len 1 $STEP $MAX "$PAR -m     6 -t  3000 -i "
run makwa            i_len 1 $STEP $MAX "$PAR -m     0 -t 30000 -i "
run parallel         i_len 1 $STEP $MAX "$PAR -m     0 -t    11 -i "
run pomelo           i_len 1 $STEP $MAX "$PAR -m     0 -t    13 -i "
run pomelo-sse       i_len 1 $STEP $MAX "$PAR -m     0 -t    14 -i "
run pufferfish       i_len 1 $STEP $MAX "$PAR -m     0 -t    12 -i "
run yescrypt         i_len 1 $STEP $MAX "$PAR -m    10 -t     1 -i "
run yescrypt-sse     i_len 1 $STEP $MAX "$PAR -m    10 -t    10 -i "

# G4 output len 1-MAX, mcost, tcost, input fixed
PAR="-h -s 16 -i 32 "
MAX=300
STEP=1
run argon            o_len 1 $STEP $MAX "$PAR -m     0 -t   2000 -o "
run argon-aesni      o_len 1 $STEP $MAX "$PAR -m     0 -t   1500 -o "
run argon2d          o_len 1 $STEP $MAX "$PAR -m   100 -t    255 -o "
run argon2i          o_len 1 $STEP $MAX "$PAR -m   100 -t   2000 -o "
run battcrypt        o_len 1 $STEP $MAX "$PAR -m     0 -t     17 -o "
run catena-dragonfly o_len 1 $STEP $MAX "$PAR -m    14 -t    100 -o "
run catena-butterfly o_len 1 $STEP $MAX "$PAR -m    10 -t     60 -o "
run lyra2            o_len 1 $STEP $MAX "$PAR -m     6 -t   2000 -o "
run lyra2-sse        o_len 1 $STEP $MAX "$PAR -m     6 -t   3000 -o "
run makwa            o_len 1 $STEP $MAX "$PAR -m     0 -t  30000 -o "
run parallel         o_len 1 $STEP $MAX "$PAR -m     0 -t     11 -o "
run pomelo           o_len 1 $STEP $MAX "$PAR -m     0 -t     13 -o "
run pomelo-sse       o_len 1 $STEP $MAX "$PAR -m     0 -t     14 -o "
run pufferfish       o_len 1 $STEP $MAX "$PAR -m     0 -t     12 -o "
run yescrypt         o_len 1 $STEP $MAX "$PAR -m    10 -t      1 -o "
run yescrypt-sse     o_len 1 $STEP $MAX "$PAR -m    10 -t     10 -o "
